# Apache-2.0 License
# Author: akoodoy@capilot.ru  
# Repository: https://github.com/momentics/CallAnnotate

version: '3.8'

services:
  callannotate:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: callannotate
    ports:
      - "8000:8000"
    volumes:
      - ../volume:/volume
      - ../config:/app/config:ro
    environment:
      - PYTHONPATH=/app/src
      - CONFIG_PATH=/app/config/default.yaml
      - VOLUME_PATH=/volume
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  callannotate_volume:
    driver: local

