# config/default.yaml
# Основные настройки сервиса CallAnnotate.
# Значения по умолчанию синхронизированы с Pydantic-моделями в src/app/config.py.

# Секция сервера
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  log_level: "info"
  version: "1.0.0"

# Секция очереди задач
queue:
  # Путь к каталогу volume с поддиректорями
  volume_path: "./volume"
  max_concurrent_tasks: 2
  max_queue_size: 100
  task_timeout: 3600
  cleanup_interval: 300

# Секция файлов
files:
  max_size: 524288000
  allowed_formats:
    - "wav"
    - "mp3"
    - "ogg"
    - "flac"
    - "aac"
    - "m4a"
    - "mp4"
  temp_cleanup_hours: 24

# Секция логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./volume/logs/system/app.log"
  external_levels:
    uvicorn: "INFO"
    fastapi: "INFO"
    asyncio: "WARNING"

cors:
  origins:
    - "*"
  allow_credentials: true
  allow_methods:
    - "*"
  allow_headers:
    - "*"

api:
  base_path: "/api/v1"

# Конфигурация этапа предобработки аудио (PreprocessingStage)
preprocess:
  # === Конфигурация DeepFilterNet (улучшение речи) ===
  deepfilter_enabled: true            # Включить DeepFilterNet обработку
  deepfilter_sample_rate: 48000       # Частота дискретизации для DeepFilterNet (похоже 48kHz)
  # === Основные параметры обработки ===
  model: "DeepFilterNet2"              # Модель для улучшения речи (DeepFilterNet2)
  device: "cpu"                        # Устройство вычислений (cpu/cuda)
  chunk_duration: 10.0                 # Длительность чанка в секундах
  overlap: 0.5                         # Перекрытие между чанками в секундах
  target_rms: -20.0                    # Целевой RMS уровень в дБFS
  
  # === Конфигурация SoX (системный аудиопроцессор) ===
  sox_enabled: false                  # Включить предварительную обработку SoX
  sox_noise_profile_duration: 2.0     # Длительность для создания профиля шума (сек)
  sox_noise_reduction: 0.3            # Коэффициент подавления шума (0.0-1.0)
  sox_gain_normalization: true        # Применять автоматическую нормализацию усиления
  
  # === Конфигурация RNNoise (нейронное шумоподавление) ===
  rnnoise_enabled: true               # Включить RNNoise шумоподавление
  rnnoise_sample_rate: 48000          # Частота дискретизации для RNNoise (только 48kHz)
  
  # === Параметры выходных файлов ===
  output_suffix: "_processed"         # Суффикс для обработанного файла
  audio_format: "wav"                 # Формат выходного аудио (wav/flac/ogg)
  bit_depth: 16                       # Глубина битов PCM (16/24/32)
  channels: "mono"                    # Количество каналов (mono/stereo/original)
  sample_rate_target: null            # Целевая частота дискретизации (null = сохранить исходную)
  
  # === Параметры обработки ===
  chunk_overlap_method: "linear"      # Метод склеивания чанков (linear/windowed)
  processing_threads: 1               # Количество потоков для параллельной обработки
  memory_limit_mb: 1024              # Лимит использования памяти в МБ
  
  # === Служебные параметры ===
  temp_cleanup: true                  # Автоматическая очистка временных файлов
  preserve_original: true             # Сохранять оригинальный файл
  debug_mode: false                   # Режим отладки с дополнительным логированием
  save_intermediate: false            # Сохранять промежуточные результаты
  progress_interval: 10               # Интервал отчета о прогрессе (%)

# секция диаризации
diarization:
  model: "pyannote/speaker-diarization-3.1"
  use_auth_token: null
  device: "cpu"
  batch_size: 32
  # параметры скользящего окна
  window_enabled: true   # включает режим windowed-diariazation
  window_size: 30.0       # длина окна в секундах
  hop_size: 10.0          # шаг окна в секундах


# Этап транскрипции (OpenAI Whisper)
transcription:
  model: "openai/whisper-base"       # Унифицировано: upgrade до base
  device: "cpu"                      # TRANSCRIPTION_DEVICE
  language: "ru"                     # TRANSCRIPTION_LANGUAGE ("auto" для автоопределения)
  batch_size: 16                     # TRANSCRIPTION_BATCH_SIZE
  task: "transcribe"                 # TRANSCRIPTION_TASK ("translate" для перевода)
  # Новые параметры для Phase 6
  metrics:
    confidence: true                 # Сбор avg confidence
    avg_logprob: true                # Сбор avg logprob
    no_speech_prob: true             # Сбор avg no_speech_prob
    timing: true                     # Сбор времени транскрипции


# Этап распознавания (SpeechBrain + FAISS)
recognition:
  model: "speechbrain/spkrec-ecapa-voxceleb"  # RECOGNITION_MODEL
  device: "cpu"                              # RECOGNITION_DEVICE
  threshold: 0.7                             # RECOGNITION_THRESHOLD
  embeddings_path: "./volume/models/embeddings" # RECOGNITION_EMBEDDINGS_PATH
  index_path: null                           # RECOGNITION_INDEX_PATH

voices:
  - name: alice_ivanova
    embedding: "./volume/models/embeddings/alice_ivanova.vec"
    phone: "+78001234567"
    description: "Голос Алисы Ивановой"


# Этап CardDAV (связывание контактов)
carddav:
  enabled: true        # CARDDAV_ENABLED
  url: null            # CARDDAV_URL
  username: null       # CARDDAV_USERNAME
  password: null       # CARDDAV_PASSWORD
  timeout: 30          # CARDDAV_TIMEOUT (сек)
  verify_ssl: true     # CARDDAV_VERIFY_SSL

# Информация о голосах (список пуст по умолчанию)
voices: []

# Настройки уведомлений
notifications:
  webhooks:
    enabled: true
    timeout: 30
    retry_count: 3
    retry_delay: 5
  websocket:
    ping_interval: 30
    ping_timeout: 10
    close_timeout: 10

# Параметры производительности
performance:
  cpu_cores: 4
  memory_limit: "3GB"
  temp_dir: "/tmp/callannotate"
  parallel_processing: true

# Безопасность и лимитирование
security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  file_upload:
    virus_scan: false
    content_validation: true

# Мониторинг и метрики
monitoring:
  metrics_enabled: true
  health_check_interval: 60
  performance_logging: true

# Фичи сервиса
features:
  real_time_processing: true
  batch_processing: true
  webhook_callbacks: true
  file_download: true
  task_cancellation: true
  progress_tracking: true
