# Конфигурация CallAnnotate
# Автор: akoodoy@capilot.ru
# С: https://github.com/momentics/CallAnnotate
# Лицензия: Apache-2.0

# Настройки сервера
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  log_level: "info"

# CORS настройки
cors:
  origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# Настройки очереди задач
queue:
  max_concurrent_tasks: 2
  max_queue_size: 100
  task_timeout: 3600  # 1 час в секундах
  cleanup_interval: 300 # 5 минут в секундах
  volume_path: "./volume"

# Настройки логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./volume/logs/system/app.log"
  external_levels:
    uvicorn: "INFO"
    fastapi: "INFO"
    asyncio: "WARNING"

# Настройки диаризации
diarization:
  model: "pyannote/speaker-diarization-3.1"
  device: "cpu" # или "cuda" если доступен GPU
  batch_size: 32
  use_auth_token: null # HuggingFace токен если требуется

# Настройки транскрипции
transcription:
  model: "openai/whisper-base"
  device: "cpu"
  language: "ru" # или "auto" для автоопределения
  batch_size: 16
  task: "transcribe" # или "translate"

# Настройки распознавания голосов
recognition:
  model: "speechbrain/spkrec-ecapa-voxceleb"
  device: "cpu"
  threshold: 0.7 # порог для распознавания
  embeddings_path: "./volume/models/embeddings"

# Настройки CardDAV
carddav:
  enabled: true
  url: "https://carddav.example.com"
  username: "user"
  password: "password"
  timeout: 30
  verify_ssl: true

# Известные голоса и их эмбеддинги
voices:
  - name: "Иван Петров"
    embedding: "./volume/models/embeddings/ivan_petrov.vec"
    phone: "+7-900-123-45-67"
    description: "Менеджер проекта"
    
  - name: "Мария Сидорова"
    embedding: "./volume/models/embeddings/maria_sidorova.vec"
    phone: "+7-900-765-43-21"
    description: "Технический директор"

# Настройки обработки файлов
files:
  max_size: 524288000 # 500MB в байтах
  allowed_formats: ["wav", "mp3", "ogg", "flac", "aac", "m4a", "mp4"]
  temp_cleanup_hours: 24

# Настройки уведомлений
notifications:
  webhooks:
    enabled: true
    timeout: 30
    retry_count: 3
    retry_delay: 5
    
  websocket:
    ping_interval: 30
    ping_timeout: 10
    close_timeout: 10

# Настройки производительности
performance:
  cpu_cores: 4
  memory_limit: "3GB"
  temp_dir: "/tmp/callannotate"
  parallel_processing: true
  
# Настройки безопасности
security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  
  file_upload:
    virus_scan: false
    content_validation: true

# Настройки мониторинга
monitoring:
  metrics_enabled: true
  health_check_interval: 60
  performance_logging: true
  
# Дополнительные опции
features:
  real_time_processing: true
  batch_processing: true
  webhook_callbacks: true
  file_download: true
  task_cancellation: true
  progress_tracking: true
