# Конфигурация CallAnnotate
# Автор: akoodoy@capilot.ru
# Ссылка: https://github.com/momentics/CallAnnotate
# Лицензия: Apache-2.0

server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1
  version: "1.0.0"

cors:
  origins: ["*"]
  allow_methods: ["*"]
  allow_headers: ["*"]
  allow_credentials: true

queue:
  volume_path: "./volume"
  max_concurrent_tasks: 2
  max_queue_size: 100
  task_timeout: 3600
  cleanup_interval: 300

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./volume/logs/app.log"

files:
  max_size: 524288000
  allowed_formats: ["wav","mp3","ogg","flac","aac","m4a","mp4"]

performance:
  temp_dir: "./volume/temp"
  cpu_cores: 4
  memory_limit: "3GB"
  parallel_processing: true

security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  file_upload:
    virus_scan: false
    content_validation: true

monitoring:
  metrics_enabled: true
  health_check_interval: 60
  performance_logging: true

features:
  real_time_processing: true
  batch_processing: true
  webhook_callbacks: true
  file_download: true
  task_cancellation: true
  progress_tracking: true
