# Apache-2.0 License
# Author: akoodoy@capilot.ru
# Repository: https://github.com/mics/CallAnnotate

server:
  host: "0.0.0.0"
  port: 8000

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rotate:
    when: midnight
    backup_count: 7

carddav:
  url: "https://carddav.example.com"
  username: "user@example.com"
  password: "changeme"
  contact_group: "CallAnnotate Contacts"

paths:
  volume_path: "/volume"
  transcription_model: "default-model"
  diarization_model: "default-model"
  max_file_size: 1073741824  # 1 GB
  supported_formats:
    - wav
    - mp3
    - flac
    - opus
