# config/default.yaml
# Основные настройки сервиса CallAnnotate.
# Значения по умолчанию синхронизированы с Pydantic-моделями в src/app/config.py.

# Секция сервера
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  log_level: "info"
  version: "1.1.0"

# Секция очереди задач
queue:
  # Путь к каталогу volume с поддиректорями
  volume_path: "./volume"
  max_concurrent_tasks: 2
  max_queue_size: 100
  task_timeout: 3600
  cleanup_interval: 300

# Секция файлов
files:
  max_size: 524288000
  allowed_formats:
    - "wav"
    - "mp3"
    - "ogg"
    - "flac"
    - "aac"
    - "m4a"
    - "mp4"
  temp_cleanup_hours: 24

# Секция логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./volume/logs/system/app.log"
  external_levels:
    uvicorn: "INFO"
    fastapi: "INFO"
    asyncio: "WARNING"

cors:
  origins:
    - "*"
  allow_credentials: true
  allow_methods:
    - "*"
  allow_headers:
    - "*"

api:
  base_path: "/api/v1"


# cекция preprocess
preprocess:
  model: "DeepFilterNet2"       # имя модели для предобработки
  device: "cpu"                 # устройство для вычислений
  chunk_duration: 2.0           # продолжительность чанка в секундах
  overlap: 0.5                  # доля перекрытия между чанками (в секундах)
  target_rms: -20.0             # целевой уровень RMS в дБFS


# Этап диаризации (pyannote.audio)
diarization:
  model: "pyannote/speaker-diarization-3.1"  # DIARIZATION_MODEL
  use_auth_token: null                      # DIARIZATION_USE_AUTH_TOKEN
  device: "cpu"                             # DIARIZATION_DEVICE
  batch_size: 32                            # DIARIZATION_BATCH_SIZE

# Этап транскрипции (OpenAI Whisper)
transcription:
  model: "openai/whisper-base"  # TRANSCRIPTION_MODEL
  device: "cpu"                 # TRANSCRIPTION_DEVICE
  language: "ru"                # TRANSCRIPTION_LANGUAGE ("auto" для автоопределения)
  batch_size: 16                # TRANSCRIPTION_BATCH_SIZE
  task: "transcribe"            # TRANSCRIPTION_TASK ("translate" для перевода)

# Этап распознавания (SpeechBrain + FAISS)
recognition:
  model: "speechbrain/spkrec-ecapa-voxceleb"  # RECOGNITION_MODEL
  device: "cpu"                              # RECOGNITION_DEVICE
  threshold: 0.7                             # RECOGNITION_THRESHOLD
  embeddings_path: null                      # RECOGNITION_EMBEDDINGS_PATH
  index_path: null                           # RECOGNITION_INDEX_PATH

# Этап CardDAV (связывание контактов)
carddav:
  enabled: true        # CARDDAV_ENABLED
  url: null            # CARDDAV_URL
  username: null       # CARDDAV_USERNAME
  password: null       # CARDDAV_PASSWORD
  timeout: 30          # CARDDAV_TIMEOUT (сек)
  verify_ssl: true     # CARDDAV_VERIFY_SSL

# Информация о голосах (список пуст по умолчанию)
voices: []

# Настройки уведомлений
notifications:
  webhooks:
    enabled: true
    timeout: 30
    retry_count: 3
    retry_delay: 5
  websocket:
    ping_interval: 30
    ping_timeout: 10
    close_timeout: 10

# Параметры производительности
performance:
  cpu_cores: 4
  memory_limit: "3GB"
  temp_dir: "/tmp/callannotate"
  parallel_processing: true

# Безопасность и лимитирование
security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  file_upload:
    virus_scan: false
    content_validation: true

# Мониторинг и метрики
monitoring:
  metrics_enabled: true
  health_check_interval: 60
  performance_logging: true

# Фичи сервиса
features:
  real_time_processing: true
  batch_processing: true
  webhook_callbacks: true
  file_download: true
  task_cancellation: true
  progress_tracking: true
