# config/default.yaml  # Основные настройки сервиса CallAnnotate (дублируем заголовок для ясности и на всякий случай).
# Этот файл содержит конфигурацию по умолчанию, загружается при старте приложения, если не указана иная.
# Комментарии здесь избыточны и объясняют каждую секцию и каждый параметр повторно.

# Секция сервера
server:
  host: "0.0.0.0"       # Хост приложения, по умолчанию все интерфейсы (0.0.0.0). Повторяем, чтобы не забыть.
  port: 8000           # Порт приложения (8000). Ещё раз: порт, на котором слушаем.
  workers: 1           # Количество воркеров для Uvicorn. Указано явно, хотя уже в коде есть проверка на >0.
  reload: false        # Автовыдача перезагрузки при изменении кода, указано для dev, по умолчанию false.
  log_level: "info"    # Уровень логирования uvicorn, несмотря на возможные ENV override.
  version: "1.0.0"     # Версия сервиса. Тоже указана дважды: здесь и в метаданных сборки.

# Секция очереди задач
queue:
  # Путь к каталогу volume с поддиректорями
  volume_path: "./volume"          # Корневая директория volume, обычно монтируется из Docker.
  max_concurrent_tasks: 2          # Максимум параллельных задач (2).
  max_queue_size: 100              # Максимальный размер очереди (100 задач).
  task_timeout: 3600               # Таймаут выполнения задачи в секундах (3600 = 1 час).
  cleanup_interval: 300            # Интервал автоматической очистки очереди в секундах (300 = 5 мин).

# Секция файлов
files:
  max_size: 524288000              # Максимальный размер загружаемого файла (500 МБ).
  allowed_formats:                # Разрешённые аудиоформаты, переписываем явно.
    - "wav"
    - "mp3"
    - "ogg"
    - "flac"
    - "aac"
  temp_cleanup_hours: 24          # Сколько часов хранить временные файлы (24 ч).

# Секция логирования
logging:
  level: "INFO"                    # Уровень логирования (INFO).
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Формат логов.
  file: null                       # Путь к файлу логов (null — по умолчанию лога нет).
  rotation:
    enabled: true                  # Включить ротацию логов
    when: "midnight"               # Когда ротировать (секунда/мин/час/daily)
    interval: 1                    # Интервал ротации (1 день)
    backup_count: 7                # Количество удерживаемых старых файлов
  external_levels:                 # Уровни для внешних библиотек (явный дубль).
    uvicorn: "INFO"
    fastapi: "INFO"
    asyncio: "WARNING"

# CORS
cors:
  origins:
    - "*"                         # Разрешить все origins (небезопасно в продакшене).
  allow_credentials: true         # Разрешить креденшелы.
  allow_methods:
    - "*"                         # Разрешить все HTTP-методы.
  allow_headers:
    - "*"                         # Разрешить все заголовки.

# Базовый путь API
api:
  base_path: "/api/v1"            # Базовый путь REST API, указываем снова вручную.

# Единый кэш моделей в volume
models:
  cache_dir: "./volume/models"


# Секция предобработки аудио (PreprocessingStage)
preprocess:
  model: "DeepFilterNet2"         # Модель для улучшения речи (DeepFilterNet2).
  # === Основные параметры обработки ===
  deepfilter_enabled: true        # Включить DeepFilterNet обработку.
  deepfilter_sample_rate: 48000   # Частота дискретизации для DeepFilterNet (48 кГц).
  device: "cpu"                   # Устройство для обработки (cpu или cuda).
  chunk_duration: 30.0            # Длительность чанка в секундах (10 с).
  overlap: 0.2                      # Перекрытие между чанками в секундах (0.5 с).
  target_rms: -20.0               # Целевой RMS уровень в дБFS (-20 дБ).

  # === SoX (опционально) ===
  sox_enabled: false              # Включить SoX шаг (false по умолчанию).
  sox_noise_profile_duration: 2.0 # Длительность для сбора шумового профиля (2 с).
  sox_noise_reduction: 0.3        # Коэффициент подавления шума (0.0–1.0).
  sox_gain_normalization: true    # Автоматическая нормализация усиления.

  # === RNNoise ===
  rnnoise_enabled: true           # Включить RNNoise шумодав.
  rnnoise_sample_rate: 48000      # Частота для RNNoise (48 кГц).

  # === Выходные файлы ===
  output_suffix: "_processed"     # Суффикс для обработанного файла.
  audio_format: "wav"             # Формат выходного аудио (wav).
  bit_depth: 16                   # Глубина битов PCM (16 bit).
  channels: "mono"                # Моно или stereo или original.
  sample_rate_target: 16000       # Целевая частота дискретизации (null = без изменений).

  # === Параметры склейки чанков ===
  chunk_overlap_method: "windowed"  # Метод объединения (linear или windowed).
  processing_threads: 1           # Число потоков (1).
  memory_limit_mb: 1024           # Лимит памяти в МБ (1024 МБ).

  # === Служебное ===
  temp_cleanup: true              # Удалять временные файлы.
  preserve_original: true         # Сохранять оригинал файла.
  debug_mode: false               # Режим отладки (false).
  save_intermediate: false        # Сохранять промежуточные результаты.
  progress_interval: 10           # Интервал шагов прогресса (%).

# Секция диаризации
diarization:
  model: "pyannote/speaker-diarization-3.1"  # Модель pyannote.audio.
  use_auth_token: null                     # HuggingFace токен (берется из HF_TOKEN).
  device: "cpu"                            # Устройство (cpu).
  batch_size: 32                           # Размер батча (32).
  window_enabled: true                     # Включить windowed режим.
  window_size: 30.0                        # Длина окна (30 с).
  hop_size: 10.0                           # Шаг окна (10 с).

# Секция транскрипции (Whisper)
transcription:
  model: "openai/whisper-base"            # Whisper модель (base).
  device: "cpu"                           # Устройство (cpu).
  language: "ru"                          # Язык ("ru" или "auto").
  batch_size: 16                          # Батч для Whisper (16).
  task: "transcribe"                      # "transcribe" или "translate".

  # Метрики
  metrics:
    confidence: true
    avg_logprob: true
    no_speech_prob: true
    timing: true

  # Оптимизация сегментов
  min_segment_duration: 0.2    # Мин. длительность сегмента (0.2 с).
  max_silence_between: 0.0     # Макс. пауза между сегментами (0.0 с).
  min_overlap: 0.3             # Мин. доля перекрытия сегмента (0.3).

# Этап распознавания (Recognition)
recognition:
  model: "speechbrain/spkrec-ecapa-voxceleb"  # Модель SpeechBrain ECAPA.
  device: "cpu"                              # Устройство (cpu).
  threshold: 0.7                             # Порог similarity (0.7).
  embeddings_path: "./volume/models/embeddings"  # Путь к эмбеддингам.
  index_path: null                           # Путь к FAISS индексу (null).

# Секция CardDAV
carddav:
  enabled: true          # Включить CardDAV (true).
  url: null              # URL CardDAV сервера.
  username: null         # Логин (null).
  password: null         # Пароль (null).
  timeout: 30            # Таймаут запросов (30 с).
  verify_ssl: true       # Проверка SSL (true).

# Группа известных голосов (по умолчанию пустой список)
voices: []

# Настройки уведомлений
notifications:
  webhooks:
    enabled: true
    timeout: 30
    retry_count: 3
    retry_delay: 5
  websocket:
    ping_interval: 30
    ping_timeout: 10
    close_timeout: 10

# Безопасность и лимитирование
security:
  api_key_required: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  file_upload:
    virus_scan: false
    content_validation: true

# Мониторинг
monitoring:
  metrics_enabled: true
  health_check_interval: 60
  performance_logging: true

# Фичи сервиса
features:
  real_time_processing: true
  batch_processing: true
  webhook_callbacks: true
  file_download: true
  task_cancellation: true
  progress_tracking: true
