name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  release:
#   types: [ published ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CallAnnotate repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'src/requirements.txt'

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1-dev

      # Добавлена предустановка Rust для сборки deepfilternet
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          # Установка deepfilternet, требующая Rust
          pip install deepfilternet

      - name: Run tests
        run: pytest tests/

      - name: Check NOTICE file completeness
        run: |
          python scripts/check_notice_completeness.py

#  build-docker:
#    name: Build Docker on Release
#    runs-on: ubuntu-latest
#    needs: build-and-test
#    if: github.event_name == 'release' && github.event.action == 'published'
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Build Docker image
#        run: |
#          docker build \
#            --file docker/Dockerfile \
#            --tag capilot/callannotate:latest \
#            .
